// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOtYvi6OBpBKC6YIuB8zBuaUrBGN_6iPI',
    appId: '1:1091999412961:web:31c4423e46f91d0796fda0',
    messagingSenderId: '1091999412961',
    projectId: 'shamify-e491e',
    authDomain: 'shamify-e491e.firebaseapp.com',
    storageBucket: 'shamify-e491e.firebasestorage.app',
    measurementId: 'G-HGJF9KJ4BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN93Fjqm2zd_Q2dTINC71dwY_8IE_hoPg',
    appId: '1:1091999412961:android:0cb3bc9ad1ce640896fda0',
    messagingSenderId: '1091999412961',
    projectId: 'shamify-e491e',
    storageBucket: 'shamify-e491e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOtYvi6OBpBKC6YIuB8zBuaUrBGN_6iPI',
    appId: '1:1091999412961:web:818c1701b0939a7596fda0',
    messagingSenderId: '1091999412961',
    projectId: 'shamify-e491e',
    authDomain: 'shamify-e491e.firebaseapp.com',
    storageBucket: 'shamify-e491e.firebasestorage.app',
    measurementId: 'G-WE0KYJBT7W',
  );
}
